### ISSUE TITLE
Should switch to Python 3

### ISSUE THREAD

**Issue by sbrun** [grwl/sslcaudit#52]
Python 2.x will no longer be supported by their upstream developers in 2020. Thus Debian developers are actively removing Python 2 support in Debian Testing with the goal of getting rid of Python 2 in Debian 11 (bullseye).
Kali is tracking Debian Testing and is thus affected by this. You should consider to switch sslcaudit to Python 3.

FWIW this is tracked in https://gitlab.com/kalilinux/packages/sslcaudit/issues/1 on the Kali side.

**Comment by abbbe** [comment]
Dear Sophie,

sslcaudit tool is outdated and not supported anymore. It is replaced by
qsslcaudit available here:
https://github.com/gremwell/qsslcaudit#debian--kali. It works on debian and
kali.

I have opened a ticket with Kali asking to outphase sslcaudit and add
qsslcaudit instead https://bugs.kali.org/view.php?id=5177, but it was not
handled.

Could you please tell me what should I do to have sslcaudit tool removed
and qsslcaudit added to Kali?

Best regards,
Alex

**Comment by sbrun** [comment]
Hello,

Thank for your quick answer.
I will reopen the Kali issue and ask the Kali team if they want me to package the new tool qsslcaudit.

Regards,
Sophie
